#kubernetes/base/airbyte/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - volumes.yaml
  - db/deployment.yaml
  - db/service.yaml
  - server/deployment.yaml
  - server/service.yaml
  - worker/deployment.yaml
  - webapp/deployment.yaml
  - webapp/service.yaml