#kubernetes/base/airbyte/volumes.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-config-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: immediate # Use the 'immediate' storage class defined elsewhere
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-workspace-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: immediate # Ensure consistent storage class
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-tmp-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: immediate # Ensure consistent storage class
  resources:
    requests:
      storage: 5Gi