apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - pvc.yaml
  - deployment.yaml

# This will be patched per environment
secretGenerator:
  - name: postgres-secret
    literals:
      - password=CHANGE_ME
    options:
      disableNameSuffixHash: true