#/kubernetes/base/postgres/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim # PVC for PostgreSQL data storage
metadata:
  name: postgres-pvc # Name of the PVC
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Ensure PVC is created before other resources
spec:
  accessModes:
    - ReadWriteOnce # PostgreSQL typically requires ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Adjust size as needed
  storageClassName: standard # Adjust based on your cluster's storage class