#/kubernetes/base/pgadmin/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  annotations:
    argocd.argoproj.io/sync-wave: "13"  # Ensure pgAdmin service is created after Postgres
  labels:
    app: pgadmin
spec:
  ports:
  - port: 80          # Service port
    targetPort: 80    # Container port
    nodePort: 30080   # Optional: For NodePort type (30000-32767)
  selector:
    app: pgadmin
  type: NodePort      # For local access; use LoadBalancer in cloud